# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mycroft Home Assistant skill

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  job-vm:

    runs-on: ubuntu-latest

    env:
        HASS_SERVER: http://127.0.0.1:8123
        HASS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmMzI5NmEzYTA0ZDc0NTI3OGUzMDIzN2I5MDlmYmM5MSIsImlhdCI6MTU5ODczMzU5MywiZXhwIjoxOTE0MDkzNTkzfQ.HEGTdkF5tt473J3WktjUIb71x06tZwcZUjp070QzLec
        TERM: xterm

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pycodestyle
        pip install pytest-cov
        pip install python-coveralls
        pip install coverage

    - name: Lint with flake8
      # stop the build if there are Python syntax errors or undefined names
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics

    # - name: Test with pytest
    #   run: |
    #     pytest

    - name: list workflow dir
      run: ls -al ${{ github.workspace }}

    # Codestyle
    - name: codestyle - Create dir for logs
      run: mkdir -p ${{ github.workspace }}/codestyle

    - name: codestyle - Check __init__.py
      run: pycodestyle --max-line-length=127 __init__.py >> ${{ github.workspace }}/codestyle/__init__.log

    - name: codestyle - Check ha_client.py
      run: pycodestyle --max-line-length=127 ha_client.py >> ${{ github.workspace }}/codestyle/ha_client.log

    # Copy skill befor HA kicks in
    - name: skill - Copy skill to mycroft
      run: |
        mkdir -p /opt/mycroft/skills/homeassistant.mycroftai
        cp -R ${{ github.workspace }}/* /opt/mycroft/skills/homeassistant.mycroftai
        ls -al /opt/mycroft/skills/homeassistant.mycroftai
        cp ${{ github.workspace }}/test/travis-ci/Mycroft/settingsmeta.yaml /opt/mycroft/skills/homeassistant.mycroftai/
        cp ${{ github.workspace }}/test/travis-ci/Mycroft/settings.json /opt/mycroft/skills/homeassistant.mycroftai/

    # Start Home Assistant
    - name: HA - pull and start docker image
      run: |
        docker pull homeassistant/home-assistant:0.114.3
        docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v ${{ github.workspace }}/test/travis-ci/HA/:/config -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3

    # Wait for Home Assistant to start
    - name: HA - wait for start
      run: sleep 2m

    # Install Home Assistant cli tool
    - name: HA - install cli
      run: pip install homeassistant-cli

    # Set Home Assistant cli tool
    - name: HA - set cli
      run: source <(hass-cli completion bash)

    # Get base info from Home Assistant
    - name: HA - install cli
      run: hass-cli info

    # Get state info from Home Assistant
    - name: HA - install cli
      run: hass-cli state list

    # Install Mycroft
    - name: MC - install Mycroft
      run: |
        git clone https://github.com/MycroftAI/mycroft-core.git /opt/mycroft-core
        ls /opt
        cp ${{ github.workspace }}/test/travis-ci/Mycroft/dev_setup.sh /opt/mycroft-core/
        chmod +x /opt/mycroft-core/dev_setup.sh
        /opt/mycroft-core/dev_setup.sh --allow-root --travis -sm
        source /opt/mycroft-core/.venv/bin/activate
        pip install allure-behave
        /opt/mycroft-core/bin/mycroft-pip install -r ${{ github.workspace }}/requirements.txt

    # unset VIRTUAL_ENV

    # Start Mycroft
    - name: MC - pull and start docker image
      run: |
        docker pull homeassistant/home-assistant:0.114.3
        docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v ${{ github.workspace }}/test/travis-ci/HA/:/config -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3

    # Wait for MC to start
    - name: MC - wait for start
      run: sleep 4m