# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mycroft Home Assistant skill

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  job-vm:

    runs-on: ubuntu-latest

    env:
        HASS_SERVER: http://127.0.0.1:8123
        HASS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmMzI5NmEzYTA0ZDc0NTI3OGUzMDIzN2I5MDlmYmM5MSIsImlhdCI6MTU5ODczMzU5MywiZXhwIjoxOTE0MDkzNTkzfQ.HEGTdkF5tt473J3WktjUIb71x06tZwcZUjp070QzLec
        TERM: xterm

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pycodestyle

    - name: Lint with flake8
      # stop the build if there are Python syntax errors or undefined names
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics

    # Codestyle
    - name: Codestyle - Create dir for logs
      run: mkdir -p ${{ github.workspace }}/codestyle/${{ github.run_number }}

    - name: Codestyle - Check __init__.py
      run: pycodestyle --max-line-length=127 __init__.py >> ${{ github.workspace }}/codestyle/${{ github.run_number }}/__init__.log

    - name: Codestyle - Check ha_client.py
      run: pycodestyle --max-line-length=127 ha_client.py >> ${{ github.workspace }}/codestyle/${{ github.run_number }}/ha_client.log

    # Copy skill befor HA kicks in
    - name: Mycroft - Copy skill to mycroft
      run: |
        mkdir -p /opt/mycroft/skills/homeassistant.mycroftai
        cp -R ${{ github.workspace }}/* /opt/mycroft/skills/homeassistant.mycroftai
        ls -al /opt/mycroft/skills/homeassistant.mycroftai
        cp ${{ github.workspace }}/test/ci/Mycroft/settingsmeta.yaml /opt/mycroft/skills/homeassistant.mycroftai/
        cp ${{ github.workspace }}/test/ci/Mycroft/settings.json /opt/mycroft/skills/homeassistant.mycroftai/

    # Start Home Assistant
    - name: HA - pull and start docker image
      run: |
        docker pull homeassistant/home-assistant:0.114.3
        docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v ${{ github.workspace }}/test/ci/HA/:/config -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3

    # Install Mycroft
    - name: Mycroft - install Mycroft
      run: |
        git clone https://github.com/MycroftAI/mycroft-core.git /opt/mycroft-core
        ls /opt
        cp ${{ github.workspace }}/test/ci/Mycroft/dev_setup.sh /opt/mycroft-core/
        chmod +x /opt/mycroft-core/dev_setup.sh
        /opt/mycroft-core/dev_setup.sh --allow-root -ci -sm -p /opt/hostedtoolcache/Python/3.7.11/x64/bin/python
        source /opt/mycroft-core/.venv/bin/activate
        pip install allure-behave
        /opt/mycroft-core/bin/mycroft-pip install -r ${{ github.workspace }}/requirements.txt

    # Install Home Assistant cli tool
    - name: HA - install cli
      run: pip install homeassistant-cli

    # Set Home Assistant cli tool
    - name: HA - set cli
      run: source <(hass-cli completion bash)

    # Get base info from Home Assistant
    - name: HA - show base info
      run: hass-cli info

    # Get state info from Home Assistant
    - name: HA - show states
      run: hass-cli state list

    # Wait for MC to start
    - name: Mycroft - Wait for start
      run: sleep 2m

    # Clear VKtest
    - name: Mycroft - Clear VKtest
      run: /opt/mycroft-core/bin/mycroft-skill-testrunner vktest clear

    # Run VKtest
    - name: Mycroft - Run VKtest
      run: /opt/mycroft-core/bin/mycroft-skill-testrunner vktest -t homeassistant.mycroftai -f allure_behave.formatter:AllureFormatter -o ${{ github.workspace }}/allure_results

    # GH get history
    - name: Github Pages - Pull Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        repository:  Tony763/Tony763.github.io
        path: ./gh-pages
        ref: master

    # GH generate VKreport
    - name: Allure - generate report
      uses: simple-elf/allure-report-action@master
      id: allure-report
      with:
        allure_results: ${{ github.workspace }}/allure_results
        gh_pages: gh-pages/skill-homeassistant/
        allure_report: allure-report
        allure_history: gh-pages/skill-homeassistant/allure-history

    # GH get codesytyle results
    - name: Codestyle - Check ha_client.py
      if: always()
      run: cp -r ${{ github.workspace }}/codestyle ${{ github.workspace }}/gh-pages/skill-homeassistant/

    # GH publish results
    - name: Github Pages - publish results
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_MS_HA }}
        external_repository: Tony763/Tony763.github.io
        publish_dir: ${{ github.workspace }}/gh-pages
        publish_branch: master

    # GH publish link as status
    - name: State - publish link to GH
      if: always()
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'VK Test report generated'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
        target_url: https://tony763.github.io/skill-homeassistant/allure-history/${{ github.run_number }}/

# TODO: Variable with path to python?
