name: "Workflow checker"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: tony763/labeler@v3.0.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"